#! /usr/bin/env python3

#Note: use coreutils' factor if you can instead of this. Theirs is much faster and advanced
#http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/factor.c

from libs import primes
import argparse


parser = argparse.ArgumentParser(description='factorize integers')
parser.add_argument('integers', metavar='n', type=int, nargs='+')

args = parser.parse_args()

plist = primes.loadPrimes()

for n in args.integers:
    print('{} = {}'.format(n, primes.primeFactorize(n, plist)))
