#! /bin/bash

MY_DIR=${MY_DIR:-${HOME}/.mysshagent}
CMD_FILE="${MY_DIR}/sshagent.cmd"
KEY=${KEY:-${HOME}/.ssh/id_rsa_github}

if ! pidof ssh-agent >/dev/null || [ ! -f "${CMD_FILE}" ]; then
	ssh-agent -s > "${CMD_FILE}"
fi

. "${CMD_FILE}"
if [ "$(pidof ssh-agent)" != "${SSH_AGENT_PID}" ]; then
	echo "Problem with the ssh-agent" >&2
	return
fi

if ssh-add -l | gawk -v KEY="${KEY}" '{ sub(/^.*\//, "", $3); sub(/^.*\//, "", KEY); if ($3 == KEY) { b_found=1 } } END { exit(b_found) }'; then
	ssh-add "${KEY}"
fi
